### PR TITLE
Python2/3

### PR DESCRIPTION
**Pull request by netmarkjp**
apply python-modernize and do many fixes, travis become green in 2.6, 2.7, 3.6.

see also: https://github.com/netmarkjp/pynag/pull/2 https://github.com/netmarkjp/pynag/pull/3

### CODE REVIEW

**Comment by pall-valmundsson** [comment]
Thank you for this PR.

Observations and comments:

Majority of changes are converting to py3 print() and explicit conversions to list type.
Most lambdas converted to list comprehensions, the ones I know are there for performance are not changed (although some I might not remember being a performance issue).

This adds dependency on the six library. RPM SPEC not updated to reflect this (no bundling allowed). A test scenario using a built RPM as installation, in addition to the others, would be cool.

Doctests with string output aren't as nice with normal string output being replaced by six functions. Maybe the old "failing" doctests should remain but with a skip, since this is actually providing usage documentation. And with this change the documentation might be come hard to read.


This one sneaked in there: https://github.com/pynag/pynag/pull/249/commits/d05a413ebcc17d7cd586849791a12ca358d9d3dc
Since a "+" is not a valid character for a DNS hostname I'm not sure whether this should be accepted.

Also this one: https://github.com/pynag/pynag/pull/249/commits/20e78e5bb010920aa334f63c6d4554dfd35c0538
It was discussed in https://github.com/pynag/pynag/pull/244


Otherwise it looks good.
Some squashing of related commits might be nice.


@palli, care to review?

**Comment by netmarkjp** [comment]
@pall-valmundsson 

Thanks for comment.

> This adds dependency on the six library. RPM SPEC not updated to reflect this (no bundling allowed). A test scenario using a built RPM as installation, in addition to the others, would be cool.

I forget to care rpm, did https://github.com/pynag/pynag/pull/249/commits/d3cb31c0c87a398cdb485be24522070092739986
(I cannot pass build, even if in original code. so did small fix in pynag.spec)

...

**Comment by netmarkjp** [comment]
> Doctests

Actially, many doctest failed...

Especially, expect unicode output ( like this https://github.com/pynag/pynag/pull/249/files#diff-823a4a2e723fa786beffbeb44d333b99L581) tests are confusing.

before: good as document, but not correct as test

```python
>>> s.get_long_output()
u'Fatal error'
```

after: correct as test, but not so much good as document

```python
>>> s.get_long_output() == six.u(str('Fatal error'))
True 
```

Hou do you think, which is better?

**Comment by netmarkjp** [comment]
> snaked

oh, sorry.

My master already merged #244 and #248 , those are included.
(I hope those PR will marge :pray: )

**Comment by gardart** [comment]
Nice work @netmarkjp ! 
I'm going to try this out and build. @palli is the MASTER of this project so hopefully we will get his blessing on this as well :)

**Comment by erikdsjostrom** [comment]
Any updates on this?

**Comment by gardart** [comment]
Sorry for the delay, I'm going to test this code tomorrow and hopefully merge this into the master.

**Comment by gardart** [comment]
New pull request that addresses this is https://github.com/pynag/pynag/pull/257

**Pull request closed without merging**
